### PR TITLE
Add support for Localization 

### PR DESCRIPTION
**Pull request by AC40**
Add language support for German
Add language support for English

Here is bit more explanation as to what was done: 
Every view string has been turned into a `LocalizedStringKey`. This lets the App Check the string in the Localizable.string file, each of which is assigned a language in the inspector. The App then replaces the StringKey with the appropriate Language-Strings.

However, for this to work properly, the build setting `Use compiler to extract Swift Strings`. This also filters every `Text` and `TextField` as Localized String Key.

But I cannot merge this Change because conflicts arise, meaning @mikaelacaron would probably have to do that.

Image of Build Setting (though it may be under "all" instead of "basic"
image

### CODE REVIEW

**Comment by mikaelacaron** [comment]
@AC40 for this part:
> However, for this to work properly, the build setting Use compiler to extract Swift Strings. This also filters every Text and TextField as Localized String Key. But I cannot merge this Change because conflicts arise, meaning @mikaelacaron would probably have to do that.

I can handle changing the build settings, once I merge your PR, but can you please resolve the merge conflicts from the latest changes to dev? Afterwards I'll merge this PR!

Thanks so much for the work!

**Comment by AC40** [comment]
I think I removed all conflicts.

**Comment by mikaelacaron** [comment]
@AC40 It looks like what you did doesn't build the project anymore, can you revert (undo) that last commit, and I'll fix the original merge conflict

**Comment by AC40** [comment]
Okay, I put it back to the state of conflict.

**Comment by mikaelacaron** [comment]
I don't think it's fully back, there was a conflict with several files and now there's only a conflict with one. I'll look at it again and fix it

**Comment by AC40** [comment]
I could also try to merge it with the current dev branch locally and then file another PR if there still is a problem.

**Comment by mikaelacaron** [comment]
You should merge dev into your feature and then solve all merge conflicts and commit, afterwards push to this branch in GitHub

**Comment by AC40** [comment]
Okay I'll do that

**Pull request closed without merging**
