### PR TITLE
Add Requestbuilder

### LINKED ISSUE #150: FEATURE - RequestBuilder
## Describe the feature you want the app to have that it currently doesn't
*  Create a RequestBuilder for creating URLRequests in AddURLViewModel
* and maybe also in other places of the app

### PR DESCRIPTION
**Pull request by Drag0ndust**
Closes #150 

## What it Does
* Enables code coverage when performing tests
* Encapsulate functionality from the AddUrlViewmodel into a RequestBuilder object

### CODE REVIEW

**Review by mikaelacaron — CHANGES_REQUESTED** [review]
Looks good! @Drag0ndust Can you squash your commits into a single commit? Once that's done tag me in a comment and I'll merge it

(Also note I merged dev into your branch)

**Comment by Drag0ndust** [comment]
I think you can squash while
merging, can't u?

**Comment by mikaelacaron** [comment]
@Drag0ndust Part of the [contributing guidelines](https://github.com/mikaelacaron/brain-marks/blob/dev/CONTRIBUTING.md) I'd like you to squash your commits because I don't do it during the merge. If I did, the commit that's actually merged is under my name, as opposed to being under your name, so it wouldn't show that you contributed to the project

**Comment by Drag0ndust** [comment]
ok

**Comment by Drag0ndust** [comment]
@mikaelacaron commits are now squashed

**Comment by mikaelacaron** [comment]
@Drag0ndust Did you merge dev into your feature branch?

**Comment by Drag0ndust** [comment]
Was there a change? I did merge dev into my branch

**Comment by mikaelacaron** [comment]
@Drag0ndust I didn't expect to see `Logger+Ext` or any of the toolbar changes in the `AddURLView` because those are already in dev, it shouldn't show on your side, as a change?
(but I haven't looked at it in-depth yet)

**Comment by Drag0ndust** [comment]
Maybe I did something wrong while squashing, sorry

**Comment by mikaelacaron** [comment]
@Drag0ndust You should've followed steps similar to this:
https://github.com/mikaelacaron/brain-marks/pull/153#discussion_r991476370

**Comment by Drag0ndust** [comment]
I will check again. If I can't fix it I will close this PR and open a new correct one

**Pull request closed without merging**
