### PR TITLE
Share Extension

### PR DESCRIPTION
**Pull request by prabal4546**
Fix for issue #57 

## Usage
Set value of `incomingURL` directly from the share extension using `.init(SuiteName` from UserDefaults using the appGroup name and get it from the main app when you need it like in **AddURLView** as an example.

### CODE REVIEW

**Comment by mikaelacaron** [comment]
Can you send me the tutorial you used to do this?
I can't merge your change. You changed the bundle identifier and added the entitlements file

**Comment by prabal4546** [comment]
I had to change the bundle identifier since it is registered with your dev account and app won't run with it. You can change it back and it won't affect this feature.
It would only effect it if `App group` is changed, then you'd need to change the app group name in ShareViewController too. And  entitlements  file was generated since `App group` capability was added.

**Comment by mikaelacaron** [comment]
Okay! I'll look into it!

**Comment by prabal4546** [comment]
Just be sure to test this feature on a physical device not simulator

**Comment by mikaelacaron** [comment]
@prabal4546 PR is reopened

**Comment by Mcrich23** [comment]
What has to be changed for this to be accepted? @prabal4546 got way further than I am and I can build on what he has

**Comment by mikaelacaron** [comment]
@Mcrich23 Nevermind, I'll do this one, there's settings that need to be changed, but I believe only I can change them

**Pull request closed without merging**
