### PR TITLE
 Add function to highlight hashtags

### PR DESCRIPTION
**Pull request by MarshallARoss**
Progress / Closed on issue #82 Highlight Hashtags

## What it Does
* Words in tweets preceded with the # symbol will now appear highlighted in Twitter blue.
* Add function to highlight hashtags
* Add example tweets to AWS

## How I Tested
* Run the application
* Look through your collections for saved tweets containing the # symbol
* Words beginning with # will appear blue. Words with the # symbol in the middle will not be 

## Screenshot
Simulator Screen Shot - iPhone 13 Pro - 2022-10-12 at 17 42 48

### CODE REVIEW

**Comment by MarshallARoss** [comment]
Thanks @mikaelacaron. I kind of got it right after messaging. I reset everything and redid it. If I'm still having trouble in the future I'll hit you up!

**Comment by mikaelacaron** [comment]
Can you install [SwiftLint](https://github.com/realm/SwiftLint), it seems you haven't and there are 4 errors related to it when building the project. Please resolve these warnings

Screen Shot 2022-10-14 at 12 38 17 AM

**Comment by MarshallARoss** [comment]
Hi @mikaelacaron. Any attempt to shorthand these results in an error - "Binary operator '+=' cannot be applied to two 'Text' operands." Do you want to try a different approach or do you prefer I tell lint to ignore that for this function.

**Comment by mikaelacaron** [comment]
> Hi @mikaelacaron. Any attempt to shorthand these results in an error - "Binary operator '+=' cannot be applied to two 'Text' operands." Do you want to try a different approach or do you prefer I tell lint to ignore that for this function.

@MarshallARoss  Generally I don't want to comment out SwiftLint rules, but for this I'll allow it. Add `// swiftlint:disable shorthand_operator` right before the extension.

Also all your comments, fix the SwiftLint warnings for those, and all the if comments, put them _inside_ the `if { }` or `else { }`, not before them

```swift
// Check if # is at the beginning of a string
if prefixString == "" {            
   output = output + Text(" ") + hashtagText
  
 } else if prefixString.contains("\n") {
   // Check if # is at the beginning of a word preceded by blank lines
   output = output + Text(" ") + Text(prefixString) + hashtagText
   
} else {
   // if # is not at the beginning of a word do not highlight
   output = output + Text(" ") + Text(String(word))
}
```

Also for the comment before the function use Cmd + Shift + `/` which will give you this, and fill it in appropriately. This will allow your comment to show up when clicking on "quick help"
```swift
/// Description
/// - Parameter tweet:
/// - Returns:
```


On your `Tweet+Extension` you don't need to put `Optional` in front of everything, and and use line breaks to fix most of the line length violation warnings

**Comment by mikaelacaron** [comment]
@MarshallARoss I found an edge case, this [tweet](https://twitter.com/_heymikec/status/1582111738798829569?s=21): the `#help...` is highlighted when only the `#help` should be highlighted

**Comment by MarshallARoss** [comment]
Updated and resubmitted. #164

**Pull request closed without merging**
